# Generated by Django 6.0.1 on 2026-02-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaire', '0002_questionnairesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='completed_content',
            field=models.TextField(blank=True, help_text='Jinja2 template shown on the completion page. The questionnaire object is available as a context variable.'),
        ),
    ]
