# Generated by Django 6.0.1 on 2026-01-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(default='text', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormPageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('form_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormComposer.formpage')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormComposer.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form_page', 'order')},
            },
        ),
        migrations.AddField(
            model_name='formpage',
            name='questions',
            field=models.ManyToManyField(through='FormComposer.FormPageQuestion', to='FormComposer.question'),
        ),
        migrations.CreateModel(
            name='SubmissionFormPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('form_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormComposer.formpage')),
                ('submission_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormComposer.submissionform')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('submission_form', 'order')},
            },
        ),
        migrations.AddField(
            model_name='submissionform',
            name='pages',
            field=models.ManyToManyField(through='FormComposer.SubmissionFormPage', to='FormComposer.formpage'),
        ),
    ]
