# Generated by Django 6.0.1 on 2026-01-26 17:59

import FormComposer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormComposer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='processor_class',
            field=models.CharField(blank=True, choices=FormComposer.models.get_processor_choices, max_length=255, null=True),
        ),
    ]
