# Generated by Django 6.0.1 on 2026-01-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormComposer', '0002_submissionform_processor_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='avro_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
