# Generated by Django 6.0.1 on 2026-01-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormComposer', '0003_submissionform_avro_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
