# Generated by Django 6.0.1 on 2026-01-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('data', models.BinaryField()),
            ],
            options={
                'verbose_name_plural': 'Schema Registries',
                'unique_together': {('name', 'version')},
            },
        ),
    ]
