# Generated by Django 6.0.1 on 2026-01-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvroSchemaManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaregistry',
            name='namespace',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
