# Generated by Django 6.0.1 on 2026-01-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvroSchemaManager', '0002_schemaregistry_namespace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemaregistry',
            name='data',
        ),
        migrations.AddField(
            model_name='schemaregistry',
            name='avro_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
