# Generated by Django 6.0.1 on 2026-01-26 22:23

import EventManager.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_class', models.CharField(choices=EventManager.models.get_processor_choices, max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventManager.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
    ]
