# Generated by Django 6.0.1 on 2026-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0002_consumeroffset_delete_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(),
        ),
    ]
