# Generated by Django 6.0.1 on 2026-02-08 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocuSignFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_string', models.TextField(help_text='Django Template that renders to a JSON string. Form field values are available as template variables (e.g. {{ q1 }}, {{ q2 }}).')),
                ('submission_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docusign_mappings', to='FormComposer.submissionform')),
            ],
        ),
    ]
