# Generated by Django 6.0.1 on 2026-02-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocuSignIntegration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docusignfieldmapping',
            name='template_string',
            field=models.JSONField(help_text='JSON object where values can be Django Templates. Form field values are available as template variables (e.g. {{ q1 }}, {{ q2 }}).'),
        ),
    ]
