# Generated by Django 6.0.1 on 2026-02-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocuSignIntegration', '0002_alter_docusignfieldmapping_template_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docusignfieldmapping',
            name='submission_form',
        ),
    ]
