# Generated by Django 6.0.1 on 2026-02-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocuSignIntegration', '0003_remove_docusignfieldmapping_submission_form'),
        ('Questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusignfieldmapping',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docusign_mappings', to='Questionnaire.questionnaire'),
        ),
    ]
