# Generated by Django 6.0.1 on 2026-02-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocuSignIntegration', '0004_docusignfieldmapping_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docusignfieldmapping',
            name='template_string',
            field=models.JSONField(help_text='JSON object where values are Jinja2 templates. Form field values are available as variables (e.g. {{ q1 }}, {{ q2 }}). Available filters: format_tin (e.g. {{ ssn | format_tin }}).'),
        ),
    ]
